// <auto-generated />
using MicroserviceEtudiant.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MicroserviceEtudiant.Migrations
{
    [DbContext(typeof(MicroDbContext))]
    partial class MicroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MicroserviceEtudiant.Model.Etudiant", b =>
                {
                    b.Property<int>("id_etudiant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cne")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_etudiant");

                    b.ToTable("etudiants");

                    b.HasData(
                        new
                        {
                            id_etudiant = 1,
                            Nom = "Djaloud",
                            Prenom = "Louariga",
                            cne = "CNE01"
                        },
                        new
                        {
                            id_etudiant = 2,
                            Nom = "Nokri",
                            Prenom = "MIRI",
                            cne = "CNE02"
                        },
                        new
                        {
                            id_etudiant = 3,
                            Nom = "Yassine",
                            Prenom = "Hafid",
                            cne = "CNE03"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
